# İş akışına bir isim verelim
name: Zamanlanmış Tarama Scripti

on:
  # Bu iş akışını tetikleyecek olay
  schedule:
    # Cron formatında zamanlama. GitHub Actions UTC saat dilimini kullanır.
    # Türkiye saati (UTC+3) ile 11:00, UTC ile 08:00'a denk gelir.
    # "Dakika Saat Gün Ay HaftanınGünü"
    # Test için UTC 15:29 (TRT 18:29) olarak ayarlandı.
    - cron: '29 15 * * *'
  
  # Bu satır, iş akışını manuel olarak da tetikleyebilmenizi sağlar (isteğe bağlı)
  workflow_dispatch:

jobs:
  # "build" adında bir iş tanımlıyoruz
  build:
    # İşin çalışacağı sanal makine türü
    runs-on: ubuntu-latest

    steps:
      # 1. Adım: Depodaki kodları sanal makineye indir
      - name: Depoyu Kopyala
        uses: actions/checkout@v4

      # 2. Adım: Python'u kur
      - name: Python 3.10 Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Adım: Gerekli kütüphaneleri kur
      - name: Gereksinimleri Yükle
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # 4. Adım: Python script'ini çalıştır
      - name: Tarama Scriptini Çalıştır
        run: python tarama_script.py
